language: go

go:
  - 1.11.x
  - 1.12.x
go_import_path: "tdd_practice"

script:
  - go test -v ./... --cover -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)